services:
  StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  UserPostController:
    class: ../../controllers/UserPostController
    arguments: ['@UserCreator']