name: Run Tests

on:
  pull_request:
    types: ["opened", "reopened", "synchronize"]
    branches: 
      - main

jobs:
  Run-Tests:
    strategy:
      matrix:
        node-version: [18.x]
        mongodb-version: ['6.0']

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Use Node ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
      
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@v1.10.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint
      
      - name: Build
        run: npm run build --if-present

      - name: Run Tests
        run: npm run test 
      
